version: 2
percy:
  defer-uploads: true
#snapshot:
#  widths:
#    - 375
#    - 1280
#  minHeight: 1024
#  percyCSS: |
#    canvas { preserveDrawingBuffer: true; }
#  enableJavaScript: false
#  cliEnableJavaScript: false
#  disableShadowDOM: true
discovery:
  allowedHostnames:
    - cdn.playngonetwork.com
  networkIdleTimeout: 750
  launch-options:
    headless: true
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false